# ~/.streamlit/secrets.toml

[snowflake]
user = "mpatil26"
password = "Mangpa@24PuneNanded"
account = "duc33023.us-east-1"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "SALES_DATE"
schema = "SALES_DATE"
